**Dealing with data (Inconsistencies)**

In [2]:
# import required libraries
import pandas as pd

In [3]:
data = {
    'date':['2025-12-01','01-12-2025','2025/12/01','12-01-2025'],
    'country':['USA','U.S.A','America','United States'],
    'name':['John Doe','Jonh Doe','Jane Doe','Jane Doe'],
#    'name':['Iqbal','Iqbaal','Munawar','Munawwar'],
    'sales_2024':[100,200,None,200],
    'sales_2025':[None,150,300,150],
        }
df = pd.DataFrame(data)
df.head()

         date        country      name  sales_2024  sales_2025
0  2025-12-01            USA  John Doe       100.0         NaN
1  01-12-2025          U.S.A  Jonh Doe       200.0       150.0
2  2025/12/01        America  Jane Doe         NaN       300.0
3  12-01-2025  United States  Jane Doe       200.0       150.0

In [4]:
# standardizing the date format
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='coerce')
df

        date        country      name  sales_2024  sales_2025
0 2025-12-01            USA  John Doe       100.0         NaN
1        NaT          U.S.A  Jonh Doe       200.0       150.0
2        NaT        America  Jane Doe         NaN       300.0
3        NaT  United States  Jane Doe       200.0       150.0

In [5]:
# correct the name of the country
country_mapping = {
    'USA': 'Unitd Stats of America',
    'U.S.A': 'Unitd Stats of America',
    'America': 'Unitd Stats of America',
    'United States': 'Unitd Stats of America'
}
df['country'] = df['country'].replace(country_mapping)
df

        date                 country      name  sales_2024  sales_2025
0 2025-12-01  Unitd Stats of America  John Doe       100.0         NaN
1        NaT  Unitd Stats of America  Jonh Doe       200.0       150.0
2        NaT  Unitd Stats of America  Jane Doe         NaN       300.0
3        NaT  Unitd Stats of America  Jane Doe       200.0       150.0

In [8]:
# correct typographical mistakes in name
# lets assume we want to correct "Jonh Doe" with "John Doe"
df['name'] = df['name'].str.replace('Jonh Doe', 'John Doe')
#df['name'] = df['name'].replace({'Iqbaal':'Iqbal','Munawar':'Munawwar'})

df

        date                 country      name  sales_2024  sales_2025
0 2025-12-01  Unitd Stats of America  John Doe       100.0         NaN
1        NaT  Unitd Stats of America  John Doe       200.0       150.0
2        NaT  Unitd Stats of America  Jane Doe         NaN       300.0
3        NaT  Unitd Stats of America  Jane Doe       200.0       150.0

In [ ]:
# remove duplicates
df = df.drop_duplicates()
df

         date                 country      name  sales_2024  sales_2025
0  2025-12-01  Unitd Stats of America  John Doe       100.0         NaN
1  01-12-2025  Unitd Stats of America  Jonh Doe       200.0       150.0
2  2025/12/01  Unitd Stats of America  Jane Doe         NaN       300.0
3  12-01-2025  Unitd Stats of America  Jane Doe       200.0       150.0

In [9]:
# remove duplicates
df = df.drop_duplicates(subset='country')
df

        date                 country      name  sales_2024  sales_2025
0 2025-12-01  Unitd Stats of America  John Doe       100.0         NaN

In [10]:
# resolving contradictory data
# sales of 2025 should be greater then 2024
df = df.drop(df[df['sales_2024']<=df['sales_2025']].index)
df

        date                 country      name  sales_2024  sales_2025
0 2025-12-01  Unitd Stats of America  John Doe       100.0         NaN

In [12]:
# Simple Linear Regression Model in Python

from sklearn.linear_model import LinearRegression
import numpy as np

In [13]:
# Example data: X = input, y = output
X = np.array([[1], [2], [3], [4], [5]])  # Features (2D)
y = np.array([2, 4, 6, 8, 10])          # Target (1D)

In [14]:
# Create and train the model
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [15]:
# Make a prediction
prediction = model.predict([[9]])

print("Predicted value for input 9:", prediction[0])

Predicted value for input 9: 18.0